name: Build, Test and Deploy Library App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Install Dependencies
      run: npm install

    - name: Install Playwright Browsers
      run: npx playwright install

    - name: Change the backend to localhost
      run: echo "export const settings = {host:\"http://localhost:3030\"}" > src/config.js

    - name: Start the Back-End
      run: npm run server &

    - name: Start Front-End
      run: npm run start &

    - name: Execute Tests
      run: npm run test

  deploy_be:
    runs-on: ubuntu-latest
    needs: build_test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy on Production
        uses: JorgeLNJunior/render-deploy@v1.4.5
        with:
          service_id: ${{ secrets.MY_RENDER_BE_SERVICE_ID }}
          api_key: ${{ secrets.MY_RENDER_API_KEY }}
          wait_deploy: true

  deploy_fe:
    runs-on: ubuntu-latest
    needs: deploy_be
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy on Production
        uses: JorgeLNJunior/render-deploy@v1.4.5
        with:
          service_id: ${{ secrets.MY_RENDER_FE_SERVICE_ID }}
          api_key: ${{ secrets.MY_RENDER_API_KEY }}
          wait_deploy: true
